
  create table "public"."conversation" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "type" text not null default 'direct'::text,
    "created_by_user_id" uuid not null default gen_random_uuid()
      );


alter table "public"."conversation" enable row level security;


  create table "public"."conversation_member" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default gen_random_uuid(),
    "conversation_id" uuid not null
      );


alter table "public"."conversation_member" enable row level security;


  create table "public"."message" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "content" text not null,
    "sender_user_id" uuid not null default gen_random_uuid(),
    "conversation_id" uuid not null default gen_random_uuid()
      );


alter table "public"."message" enable row level security;

CREATE UNIQUE INDEX conversation_member_pkey ON public.conversation_member USING btree (id);

CREATE UNIQUE INDEX conversation_pkey ON public.conversation USING btree (id);

CREATE UNIQUE INDEX message_pkey ON public.message USING btree (id);

alter table "public"."conversation" add constraint "conversation_pkey" PRIMARY KEY using index "conversation_pkey";

alter table "public"."conversation_member" add constraint "conversation_member_pkey" PRIMARY KEY using index "conversation_member_pkey";

alter table "public"."message" add constraint "message_pkey" PRIMARY KEY using index "message_pkey";

alter table "public"."conversation" add constraint "conversation_created_by_user_id_fkey" FOREIGN KEY (created_by_user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."conversation" validate constraint "conversation_created_by_user_id_fkey";

alter table "public"."conversation_member" add constraint "conversation_member_conversation_id_fkey" FOREIGN KEY (conversation_id) REFERENCES public.conversation(id) not valid;

alter table "public"."conversation_member" validate constraint "conversation_member_conversation_id_fkey";

alter table "public"."conversation_member" add constraint "conversation_member_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."conversation_member" validate constraint "conversation_member_user_id_fkey";

alter table "public"."message" add constraint "message_conversation_id_fkey" FOREIGN KEY (conversation_id) REFERENCES public.conversation(id) not valid;

alter table "public"."message" validate constraint "message_conversation_id_fkey";

alter table "public"."message" add constraint "message_sender_user_id_fkey" FOREIGN KEY (sender_user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."message" validate constraint "message_sender_user_id_fkey";

grant delete on table "public"."conversation" to "anon";

grant insert on table "public"."conversation" to "anon";

grant references on table "public"."conversation" to "anon";

grant select on table "public"."conversation" to "anon";

grant trigger on table "public"."conversation" to "anon";

grant truncate on table "public"."conversation" to "anon";

grant update on table "public"."conversation" to "anon";

grant delete on table "public"."conversation" to "authenticated";

grant insert on table "public"."conversation" to "authenticated";

grant references on table "public"."conversation" to "authenticated";

grant select on table "public"."conversation" to "authenticated";

grant trigger on table "public"."conversation" to "authenticated";

grant truncate on table "public"."conversation" to "authenticated";

grant update on table "public"."conversation" to "authenticated";

grant delete on table "public"."conversation" to "postgres";

grant insert on table "public"."conversation" to "postgres";

grant references on table "public"."conversation" to "postgres";

grant select on table "public"."conversation" to "postgres";

grant trigger on table "public"."conversation" to "postgres";

grant truncate on table "public"."conversation" to "postgres";

grant update on table "public"."conversation" to "postgres";

grant delete on table "public"."conversation" to "service_role";

grant insert on table "public"."conversation" to "service_role";

grant references on table "public"."conversation" to "service_role";

grant select on table "public"."conversation" to "service_role";

grant trigger on table "public"."conversation" to "service_role";

grant truncate on table "public"."conversation" to "service_role";

grant update on table "public"."conversation" to "service_role";

grant delete on table "public"."conversation_member" to "anon";

grant insert on table "public"."conversation_member" to "anon";

grant references on table "public"."conversation_member" to "anon";

grant select on table "public"."conversation_member" to "anon";

grant trigger on table "public"."conversation_member" to "anon";

grant truncate on table "public"."conversation_member" to "anon";

grant update on table "public"."conversation_member" to "anon";

grant delete on table "public"."conversation_member" to "authenticated";

grant insert on table "public"."conversation_member" to "authenticated";

grant references on table "public"."conversation_member" to "authenticated";

grant select on table "public"."conversation_member" to "authenticated";

grant trigger on table "public"."conversation_member" to "authenticated";

grant truncate on table "public"."conversation_member" to "authenticated";

grant update on table "public"."conversation_member" to "authenticated";

grant delete on table "public"."conversation_member" to "postgres";

grant insert on table "public"."conversation_member" to "postgres";

grant references on table "public"."conversation_member" to "postgres";

grant select on table "public"."conversation_member" to "postgres";

grant trigger on table "public"."conversation_member" to "postgres";

grant truncate on table "public"."conversation_member" to "postgres";

grant update on table "public"."conversation_member" to "postgres";

grant delete on table "public"."conversation_member" to "service_role";

grant insert on table "public"."conversation_member" to "service_role";

grant references on table "public"."conversation_member" to "service_role";

grant select on table "public"."conversation_member" to "service_role";

grant trigger on table "public"."conversation_member" to "service_role";

grant truncate on table "public"."conversation_member" to "service_role";

grant update on table "public"."conversation_member" to "service_role";

grant delete on table "public"."message" to "anon";

grant insert on table "public"."message" to "anon";

grant references on table "public"."message" to "anon";

grant select on table "public"."message" to "anon";

grant trigger on table "public"."message" to "anon";

grant truncate on table "public"."message" to "anon";

grant update on table "public"."message" to "anon";

grant delete on table "public"."message" to "authenticated";

grant insert on table "public"."message" to "authenticated";

grant references on table "public"."message" to "authenticated";

grant select on table "public"."message" to "authenticated";

grant trigger on table "public"."message" to "authenticated";

grant truncate on table "public"."message" to "authenticated";

grant update on table "public"."message" to "authenticated";

grant delete on table "public"."message" to "postgres";

grant insert on table "public"."message" to "postgres";

grant references on table "public"."message" to "postgres";

grant select on table "public"."message" to "postgres";

grant trigger on table "public"."message" to "postgres";

grant truncate on table "public"."message" to "postgres";

grant update on table "public"."message" to "postgres";

grant delete on table "public"."message" to "service_role";

grant insert on table "public"."message" to "service_role";

grant references on table "public"."message" to "service_role";

grant select on table "public"."message" to "service_role";

grant trigger on table "public"."message" to "service_role";

grant truncate on table "public"."message" to "service_role";

grant update on table "public"."message" to "service_role";


