
  create table "public"."relationships" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_a" uuid not null,
    "user_b" uuid not null,
    "status" text not null default ''::text
      );


alter table "public"."relationships" enable row level security;

CREATE UNIQUE INDEX relationships_pkey ON public.relationships USING btree (id);

alter table "public"."relationships" add constraint "relationships_pkey" PRIMARY KEY using index "relationships_pkey";

alter table "public"."relationships" add constraint "relationships_user_a_fkey" FOREIGN KEY (user_a) REFERENCES public.profiles(id) not valid;

alter table "public"."relationships" validate constraint "relationships_user_a_fkey";

alter table "public"."relationships" add constraint "relationships_user_b_fkey" FOREIGN KEY (user_b) REFERENCES public.profiles(id) not valid;

alter table "public"."relationships" validate constraint "relationships_user_b_fkey";

grant delete on table "public"."relationships" to "anon";

grant insert on table "public"."relationships" to "anon";

grant references on table "public"."relationships" to "anon";

grant select on table "public"."relationships" to "anon";

grant trigger on table "public"."relationships" to "anon";

grant truncate on table "public"."relationships" to "anon";

grant update on table "public"."relationships" to "anon";

grant delete on table "public"."relationships" to "authenticated";

grant insert on table "public"."relationships" to "authenticated";

grant references on table "public"."relationships" to "authenticated";

grant select on table "public"."relationships" to "authenticated";

grant trigger on table "public"."relationships" to "authenticated";

grant truncate on table "public"."relationships" to "authenticated";

grant update on table "public"."relationships" to "authenticated";

grant delete on table "public"."relationships" to "postgres";

grant insert on table "public"."relationships" to "postgres";

grant references on table "public"."relationships" to "postgres";

grant select on table "public"."relationships" to "postgres";

grant trigger on table "public"."relationships" to "postgres";

grant truncate on table "public"."relationships" to "postgres";

grant update on table "public"."relationships" to "postgres";

grant delete on table "public"."relationships" to "service_role";

grant insert on table "public"."relationships" to "service_role";

grant references on table "public"."relationships" to "service_role";

grant select on table "public"."relationships" to "service_role";

grant trigger on table "public"."relationships" to "service_role";

grant truncate on table "public"."relationships" to "service_role";

grant update on table "public"."relationships" to "service_role";


